### ISSUE TITLE
Non ascii volume name support

### ISSUE THREAD

**Issue by kimlimjustin** [cristiammercado/node-disk-info#26]
![](https://user-images.githubusercontent.com/47604048/135573766-d621b83d-fa59-47d1-bb31-aa0b8c17f4ab.png)

This is originally reported on kimlimjustin/xplorer#114. I've tried to reproduce it by myself and it's the same, this is because `wmic` doesn't output the volume name correctly, `你好` became `??` on wmic output.

Maybe for Windows, could it be done by using c++ native bindings (?)

Thanks and Regards

**Comment by Ekristoffe** [comment]
hello Kim, what version of the node disk info library are you using ?
this problem should have been resolved in the 1.3.0

**Comment by kimlimjustin** [comment]
Oh, lemme try the version 1.3.0

**Comment by kimlimjustin** [comment]
I'm really sorry because this is not `node-disk-info` error since I add the patches on my project, but could you please support reading drive's `volumename`? Because `filesystem` is not equal to `volumename`,  I tried to directly parse it from `wmic` but `wmic` can't return nonascii volumename

Thanks and Regards

**Comment by Ekristoffe** [comment]
let's close this one a continue on the original `xplorer` Issue

**Comment by kimlimjustin** [comment]
Sure, I'll try the solution you provide!
